---
- hosts: localhost
  connection: local
  become: true
    
  tasks:

  - name: Update apt-get repo and cache
    apt:
      update_cache=yes 
      force_apt_get=yes 
      cache_valid_time=3600 

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install the NTP daemon to synchronize the clocks to ms.
    apt: name=ntp

  - name: Make sure ntp is started, and is enabled on restart.
    service: name=ntp state=started enabled=yes  
  
  - name: install packages
    package:
      name:
        - dconf-cli
        - python3-psutil
      state: latest  

  - name: uninstall packages
    package:
      name:
        - thunderbird
        - rhythmbox
      state: absent  

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: ubuntu
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: ubuntu
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/60"
      job: ansible-pull -o -U https://github.com/londiniumcomputers/popos.git
